taskDefinitionArn: 'arn:aws:ecs:ap-southeast-1:095257590925:task-definition/first-run-task-definition:1'
containerDefinitions:
  - {name: tomcat-webserver, image: tomcat, cpu: 1024, memoryReservation: 2048, links: [], portMappings: [{containerPort: 8080, hostPort: 8080, protocol: tcp}], essential: true, entryPoint: [], command: [], environment: [], mountPoints: [], volumesFrom: [], logConfiguration: {logDriver: awslogs, options: {awslogs-group: /ecs/first-run-task-definition, awslogs-region: ap-southeast-1, awslogs-stream-prefix: ecs}}}
family: first-run-task-definition
executionRoleArn: 'arn:aws:iam::095257590925:role/ecsTaskExecutionRole'
networkMode: awsvpc
revision: 1
volumes: []
status: ACTIVE
requiresAttributes:
  - {name: com.amazonaws.ecs.capability.logging-driver.awslogs}
  - {name: ecs.capability.execution-role-awslogs}
  - {name: com.amazonaws.ecs.capability.docker-remote-api.1.19}
  - {name: com.amazonaws.ecs.capability.docker-remote-api.1.21}
  - {name: com.amazonaws.ecs.capability.docker-remote-api.1.18}
  - {name: ecs.capability.task-eni}
placementConstraints: []
compatibilities:
  - EC2
  - FARGATE
requiresCompatibilities:
  - FARGATE
cpu: '1024'
memory: '2048'
registeredAt: '2022-05-29T16:43:45.334Z'
registeredBy: 'arn:aws:iam::095257590925:root'
tags: []
