name: Docker Image CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production

    steps:
    - uses: actions/checkout@v3
      name: Check out code

    - uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: warayout/demo-app
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - uses: muinmomin/webhook-action@v1.0.0
      with:
        url: ${{ secrets.WEBHOOK_URL }}
        data: '{"content": "🚀 build images success !!!"}'
