name: Docker Image CI

on:
  push:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest
    environment: production

    steps:
    - uses: actions/checkout@v3
      name: Check out code

    - uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'npm'
    - run: npm ci
      env:
        CLUSTER: false
        MONGO_DB: secrets.MONGO_DB
        AMQP_URL: secrets.AMQP_URL
        REDIS_URL: secrets.REDIS_URL
        REDIS_PORT: secrets.REDIS_PORT
        REDIS_USER: secrets.REDIS_USER
        REDIS_PASSWORD: secrets.REDIS_PASSWORD

    - uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: warayout/demo-app
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
